### ISSUE TITLE
Building FS image fails on Windows

### ISSUE THREAD

**Issue by d3viant** [idolpx/meatloaf-specialty#19]
On Windows 11, build and upload goes fine but attempting to build or upload the FS image results in this error:

Building in debug mode
Building FS image from 'C:\C:\Users\User\Documents\PlatformIO\Projects\meatloaf-specialty\data\BUILD_IEC' directory to .pio\build\lolin-d32-pro\spiffs.bin
error: can't read source directory
*** [.pio\build\lolin-d32-pro\spiffs.bin] Error 1

Notice the "C:\C:\" part? I can't figure out where that is, but pretty sure that's it.

**Comment by idolpx** [comment]
Update your platformio.ini from the platformio.ini.sample file and you should be good to go.  :)

**Comment by d3viant** [comment]
Nope. Still the same error. After I read your reply, I thought, "I did," but I followed your directions anyway: I performed a git pull from origin main, then I deleted my platform.ini, and renamed the sample to "platform.ini" and built and uploaded again, but get exact same error as two days ago on Upload Filesystem Image:

 *  Executing task: C:\Users\User\.platformio\penv\Scripts\platformio.exe run --target uploadfs --environment lolin-d32-pro 

Processing lolin-d32-pro (board: esp32-16mb; platform: espressif32@6.4.0; framework: espidf)
--------------------------------------------------------------------------------------------------------------------------------------
Verbose mode can be enabled via `-v, --verbose` option
Automatic versioning disabled
CONFIGURATION: https://docs.platformio.org/page/boards/espressif32/esp32-16mb.html
PLATFORM: Espressif 32 (6.4.0) > Meatloaf v1
HARDWARE: ESP32 240MHz, 4.31MB RAM, 16MB Flash
DEBUG: Current (ftdi) On-board (ftdi) External (cmsis-dap, esp-bridge, esp-prog, iot-bus-jtag, jlink, minimodule, olimex-arm-usb-ocd, olimex-arm-usb-ocd-h, olimex-arm-usb-tiny-h, olimex-jtag-tiny, tumpa)
PACKAGES:
 - framework-espidf @ 3.50101.230828 (5.1.1)
 - tool-cmake @ 3.16.4
 - tool-esptoolpy @ 1.40501.0 (4.5.1)
 - tool-idf @ 1.0.1
 - tool-mconf @ 1.4060000.20190628 (406.0.0)
 - tool-mkfatfs @ 2.0.1
 - tool-mklittlefs @ 1.203.210628 (2.3)
 - tool-mkspiffs @ 2.230.0 (2.30)
 - tool-ninja @ 1.9.0
 - tool-riscv32-esp-elf-gdb @ 11.2.0+20220823
 - tool-xtensa-esp-elf-gdb @ 11.2.0+20230208
 - toolchain-esp32ulp @ 1.23500.220830 (2.35.0)
 - toolchain-xtensa-esp32 @ 12.2.0+20230208
Reading CMake configuration...
LDF: Library Dependency Finder -> https://bit.ly/configure-pio-ldf
LDF Modes: Finder ~ deep+, Compatibility ~ soft
Found 31 compatible libraries
Scanning dependencies...
Dependency Graph
|-- hardware
|-- device
|-- bus
|-- FileSystem
|-- media
|-- meatloaf
|-- utils
|-- mfnjson
|-- network-protocol
|-- printer-emulator
|-- fnjson
|-- fuji
|-- sam
|-- display
|-- config
|-- encrypt
Building in debug mode
Building FS image from 'C:\C:\Users\User\Documents\PlatformIO\Projects\meatloaf-specialty\data\BUILD_IEC' directory to .pio\build\lolin-d32-pro\spiffs.bin
error: can't read source directory
*** [.pio\build\lolin-d32-pro\spiffs.bin] Error 1
==================================================== [FAILED] Took 25.80 seconds ====================================================

Environment    Status    Duration
-------------  --------  ------------
lolin-d32-pro  FAILED    00:00:25.802
=============================================== 1 failed, 0 succeeded in 00:00:25.802 =============================================== 

 *  The terminal process "C:\Users\User\.platformio\penv\Scripts\platformio.exe 'run', '--target', 'uploadfs', '--environment', 'lolin-d32-pro'" terminated with exit code: 1.

**Comment by mozzwald** [comment]
@d3viant 

the problem is related to this line in platformio.ini:
https://github.com/idolpx/meatloaf-specialty/blob/915158e5870ed8bb81bb3419aff64ffc25a6484f/platformio.ini.sample#L59

try removing the beginning slash. if that doesnt work, hardcode the direct path the the data dir as it resides on your system

**Comment by idolpx** [comment]
Maybe try just... this works on osx.  I will test on windows later today.
```
data_dir = data/${meatloaf.build_platform}
```
